#!/bin/bash
host_name="http://127.0.0.1:5000/"

echo "Deleting database if it exists to test init_db()"
rm -f database.db

echo "Starting server with nohup and putting it in the background"
rm -f nohup.out
. venv/bin/activate
nohup python server.py &
sleep 3

echo "The server is at ${host_name}users/, if this is incorrect, edit the host_name variable"
echo "Attempting to add a few new users"
curl -i -X POST -d "username=cj+zeiger" "${host_name}users/"
curl -i -X POST -d "username=john+doe" "${host_name}users/"
curl -i -X POST -d "username=sam+smith" "${host_name}users/"   

echo "Incrementing the count for all three users."
curl -i -X PUT "${host_name}users/cj%20zeiger"

curl -i -X PUT "${host_name}users/john%20doe"
curl -i -X PUT "${host_name}users/john%20doe"

curl -i -X PUT "${host_name}users/sam%20smith"
curl -i -X PUT "${host_name}users/sam%20smith"
curl -i -X PUT "${host_name}users/sam%20smith"

echo -e "Now requesting a list of the database \n cj zeiger should hav a count of 1 \n john doe should have a count of 2 \n sam smith should have a count of 3"

curl -i -X GET "${host_name}users/"

echo "Requesting the individual count of each user through the /users/<username> endpoint"

echo "CJ Zeiger should have a count of 1"
curl -i -X GET "${host_name}users/cj%20zeiger"

echo "John Doe should have a count of 2"
curl -i -X GET "${host_name}users/john%20doe"

echo "Sam Smith should have a count of 3"
curl -i -X GET "${host_name}users/sam%20smith"

echo "Now testing some invalid requests"

echo "Trying to make an invalid GET request to /users/ that contains form data when it should not."

curl -i -X GET -d "username=sam+smith" "${host_name}users/"

echo "Attempting a POST requesting to a specific user"
curl -i -X POST "${host_name}users/cj%20zeiger"

echo "Attampting a PUT request with a username= in the form data"
curl -i -X PUT -d "username=cj+zeiger" "${host_name}users/"

echo "Done testing with cURL"



pkill -f server.py

echo "Verifying database structure"
sqlite3 database.db 'select * from interactions'

